### ISSUE TITLE
Support template literals

### ISSUE THREAD

**Issue by rchl** [braver/TypeScriptSyntax#1]
Seems like this syntax is a little behind official javascript syntax. In JS syntax template literals are handled properly:

```js
const v = '!!!'
const s  = `This is template literal with variables ${v}`
```

In JS syntax variable stands out and pressing '$' within template literal adds braces automatically. Both of these features should be working in typescript syntax

**Comment by braver** [comment]
This is essentially just a fork to publish the syntax created by Microsoft. I don’t modify anything and don’t plan to, it’s too big and complicated and I don’t have the time. I’m not against the idea, but I’m not going to push for it myself. If you want to update the syntax, they’re the ones to talk about it. They probably can’t do much though because it’s still based on tmLanguage which they use in VS Code. At least I believe they still haven’t figured out that you can’t do a full featured syntax, or a performant parser, based on tmLanguage...

Anyway, it’s here: https://github.com/Microsoft/TypeScript-TmLanguage

**Comment by braver** [comment]
That said, I do need to get back in sync with the upstream repo...

**Comment by rchl** [comment]
I think they might already be supporting template literals, having a cursory look at their typescript.tmLanguage...

**Comment by rchl** [comment]
Hmm, but then those changes are also in this fork... Don't have time to look into it now.

I understand and thanks for explaining how things work. :)

**Comment by braver** [comment]
No problem. Was a good kick in the butt to do an update, so we're back in sync again. As to specific details about the syntax I don't know too much about it. Also haven't used TS in a while...
